### ISSUE TITLE
Getting error message when trying to create StateMachine with choice State

### ISSUE THREAD

**Issue by nayele15** [vdaron/StatesLanguage#1]
When trying to create a State Machine with a Choice state I'm getting this error message : 

![image](https://user-images.githubusercontent.com/32763811/47164938-4d472d00-d2f9-11e8-98ad-0e38f40ba37b.png)

Link of the state machine : https://textuploader.com/dnu5h

**Comment by vdaron** [comment]
Fixed in Release 1.5.0
